### PR TITLE
Add 5.16.10.17706

### PR DESCRIPTION
**Pull request by wilkinson4**

### CODE REVIEW

**Review by mieszko4 — APPROVED** [review]

**Comment by mieszko4** [comment]
I had to rebuild it because there was already broken tag. The rebuild tag is `5.16.10.17707`

**Comment by wilkinson4** [comment]
> I had to rebuild it because there was already broken tag. The rebuild tag is `5.16.10.17707`

Seems like there are some issues with the assets available in the new version in Jitpack. Did I miss something in my PR, or is this something similar to [this issue](https://github.com/mieszko4/react-native-zoom-us/issues/324)
Screenshot 2023-12-15 at 12 27 54 PM
Screenshot 2023-12-15 at 12 29 21 PM
Screenshot 2023-12-15 at 12 29 51 PM

**Comment by mieszko4** [comment]
Builds for me.
I did the following changes in https://github.com/mieszko4/react-native-zoom-us/pull/314:
```diff
diff --git a/android/build.gradle b/android/build.gradle
index 0338454..1aa0bbe 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -36,7 +36,7 @@ android {
 dependencies {
     implementation 'com.facebook.react:react-native:+' // From node_modules
 
-    implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.16.2.16555'
+    implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.16.10.17707'
 
     // Dependencies copied from mobilertc-android-studio/mobilertc/build.gradle
     // NB: We use com.google.android.flexbox:flexbox:3.0.0 because of "Could not find com.google.android:flexbox:2.0.1"
diff --git a/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java b/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
index 6b29304..9c3d51e 100644
--- a/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
+++ b/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
@@ -1128,6 +1128,10 @@ public class RNZoomUsModule extends ReactContextBaseJavaModule implements ZoomSD
   public void onLocalRecordingPrivilegeRequested(IRequestLocalRecordingPrivilegeHandler handler) {}
   @Override
   public void onRequestLocalRecordingPrivilegeChanged(LocalRecordingRequestPrivilegeStatus status) {}
+  @Override
+  public void onParticipantProfilePictureStatusChange(boolean hidden) {};
+  @Override
+  public void onAICompanionActiveChangeNotice(boolean active) {};
 
   // InMeetingShareListener event listeners
   // DEPRECATED: onShareActiveUser is just kept for now for backwards compatibility of events

```

And updated `ndkVersion = "25.2.9519653"`

**Comment by wilkinson4** [comment]
Thank you. Can confirm that I am still experiencing the issue when a non-host leaves a meeting where it takes you back to the connecting to meeting screen. We are going to reach out to zoom and try to get a meeting with one of their devs because this feels like a bug that was introduced to their SDK in version 5.16.x. I tested the same thing on 5.15.x and the issue wasn't there.

**Pull request merged**
